version: "3.9"
services:
  # web:
  #   build:
  #     context: ./docker
  #     dockerfile: web.dockerfile
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./html:/var/www/html
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel
volumes:
  dbdata: